// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWoUogym3KTV-r9uV5fJgp1KF9oZsSY6w',
    appId: '1:678405144548:web:438ce2a9ff86c9102411f1',
    messagingSenderId: '678405144548',
    projectId: 'geolore-e764f',
    authDomain: 'geolore-e764f.firebaseapp.com',
    storageBucket: 'geolore-e764f.firebasestorage.app',
    measurementId: 'G-GLVTE26VVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91Q1Zb-JOXT-e0NBgkb0FLrXHILnsb4U',
    appId: '1:678405144548:android:9d05c325a353d2e62411f1',
    messagingSenderId: '678405144548',
    projectId: 'geolore-e764f',
    storageBucket: 'geolore-e764f.firebasestorage.app',
  );
}
